/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentsignouthelper;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Brandon
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        timer.start();
    }
    //Static string to determine what screen to set visible
    public static String panel = "menuPanel";
    //The window's icon
    private Image image = new ImageIcon(this.getClass().getResource("guitar.png")).getImage();

    Timer timer = new Timer(10, new TimerListener());

    public static void checkPanel() {
        
        if (panel.equals("signOut")) {
            menuPanel.setVisible(false);
            signInPanel.setVisible(false);
            signOutPanel.setVisible(true);           
        }else if(panel.equals("addPanel")){
            //code
        }else if(panel.equals("signIn")){
            signOutPanel.setVisible(false);
            menuPanel.setVisible(false);
            signInPanel.setVisible(true);
        }else if(panel.equals("back")){
            signOutPanel.setVisible(false);
            signInPanel.setVisible(false);
            menuPanel.setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new instrumentsignouthelper.MenuPanel();
        signOutPanel = new instrumentsignouthelper.SignOutPanel();
        signInPanel = new instrumentsignouthelper.SignInPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instrument Sign Out Helper");
        setIconImage(image);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(menuPanel, "card2");
        mainPanel.add(signOutPanel, "card3");
        mainPanel.add(signInPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel mainPanel;
    private static instrumentsignouthelper.MenuPanel menuPanel;
    private static instrumentsignouthelper.SignInPanel signInPanel;
    private static instrumentsignouthelper.SignOutPanel signOutPanel;
    // End of variables declaration//GEN-END:variables

    private static class TimerListener implements ActionListener {

        public TimerListener() {
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            checkPanel();
        }
    }

}
